version: 2

jobs:
  build:
    # working_directory: ~/demo_project

    docker:
      - image: mrpossoms/ubuntu-artful-dev 
        environment:

    steps:
      - checkout

      - run:
          name: Find depends
          command: ./findlibs.sh

      - run:
          name: Compile collector
          command: make bin/collector

      - run:
          name: Compile predictor 
          command: make bin/predictor

      - run:
          name: Compile actuator 
          command: make bin/actuator

